#!/usr/bin/env python3
"""Turn tools/faces.txt into firmware/robot_body/faces_data.h."""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "faces.txt"
OUT = ROOT / "firmware" / "robot_body" / "faces_data.h"
ROWS = {"eyes": 9, "mouth": 7}


def parse(text):
    parts = {"eyes": [], "mouth": []}
    kind = name = None
    rows = []
    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#") and len(line) != 16:
            continue
        if line.split()[0] in ROWS:
            kind, name = line.split()
            rows = []
            parts[kind].append((name, rows))
            continue
        if kind is None:
            sys.exit(f"faces.txt:{n}: picture row before any 'eyes' or 'mouth' line")
        if len(line) != 16 or set(line) - set(".#"):
            sys.exit(f"faces.txt:{n}: rows must be 16 characters of '.' and '#'")
        rows.append(line)
    for kind, items in parts.items():
        for name, rows in items:
            if len(rows) != ROWS[kind]:
                sys.exit(f"{kind} {name}: needs {ROWS[kind]} rows, has {len(rows)}")
    return parts


def main():
    parts = parse(SRC.read_text())
    out = ["// Generated by tools/make_faces.py from tools/faces.txt. Do not edit by hand.",
           "#pragma once", "#include <avr/pgmspace.h>", ""]
    for kind, items in parts.items():
        prefix = "EYES" if kind == "eyes" else "MOUTH"
        out.append(f"enum {prefix.capitalize()}Id : uint8_t {{")
        out += [f"  {prefix}_{name}," for name, _ in items]
        out.append(f"  {prefix}_COUNT")
        out.append("};")
        out.append(f"const uint16_t {kind.upper()}_BITMAPS[][{ROWS[kind]}] PROGMEM = {{")
        for name, rows in items:
            vals = ", ".join(f"0x{int(r.replace('#', '1').replace('.', '0'), 2):04X}" for r in rows)
            out.append(f"  {{{vals}}},  // {name}")
        out.append("};")
        out.append("")
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(parts['eyes'])} eyes, {len(parts['mouth'])} mouths")


if __name__ == "__main__":
    main()
